<html>
<head>
    <title>Example Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Depot</h1>

<form class="pure-form" method="get" action="/depot/<?=$depot->getId()?>/updat">
    <label for="id" >ID</label>
    <input name="id" id="id" type="text" size="60" value="<?=$depot->getId()?>" /><br />
    <label for="nama">Waktu</label>
       <input name="nama" id="nama" type="date" size="60"  value="<?=$depot->getNama()?>"/><br />
	 <label for="depot">Nilai</label>
       <input name="depot" id="depot" type="text" size="60"  value="<?=$depot->getDepot()?>"/><br />
	      <label for="depot">Nama Depot</label>
    <select name="depot">
        <option value=""></option>
<?php
foreach($depot as $depot): ?>
    <option value="<?=$depot->getId()?>"><?=$depot->getDepot()?></option>
<?php
endforeach;
?>
    </select><br />
    <input type="submit" class="pure-button" value="Update" />
</form>
<?php require 'footer.php' ?>
</body>
</html>


