<html>
<head>
    <title>Homewater Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>New Depot</h1>

<form class="pure-form" method="post" action="/depot/new">
    <label for="id">ID</label>
    <input name="id" id="id" type="text" size="60" /><br />

    <label for="depot">Nama Depot</label>
       <input name="depot" id="depot" type="text" size="60" /><br />
	
    <label for="nama">Status</label>
       <input name="nama" id="nama" type="text" size="60" /><br />

    <input type="submit" class="pure-button" value="Create" />
</form>
<?php require 'footer.php' ?>
</body>
</html>


