<html>
<head>
    <title>Example Application</title>
    <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
</head>
<body>
<h1>Menu Aplikasi</h1>

<p>1. <a href="/user"> Menu Data User</a></p>
<p>2. <a href="/depot">Menu Data Depot</a></p>
<p>2. <a href="/delivery">Menu Data Depot Delivery</a></p>
<p>3. <a href="/deposit">Menu Data Deposit</a></p>
<form action="/logout" method="GET">
 <input type="submit" class="pure-button" value="Logout" />
</form>
</body>
</html>

